name: PR actions
"on":
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  app-test:
    name: app-test
    runs-on: ubuntu-latest
    steps:
      - run: "npm run test"
